In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Accuracy" : [85.36, 79.84, 96.953, 96.447, 81.733, 89.767, 95.853, 97.107],
    "cross_val_acc" : [84.6, 79.0, 96.6, 95.7, 81.0, 89.1, 95.5, 96.8],
    "roc_auc" : [85.36, 87.506, 99.039, 98.995, 89.74, 96.1, 98.927, 99.176],
    "f1_score" : [85.387, 79.781, 96.954, 96.426, 81.763, 89.682, 95.843, 97.107],
    "diff_cv_acc" : [0.407, 0.84, 0.353, 0.747, 0.733, 0.667, 0.353, 0.307],
    "speed_fit" : [1.697, 0.167, 14.949, 20.749, 16.277, 38.91, 0.364, 4.699],
    "speed_cv" : [3.897, 2.175, 23.285, 17.1, 15.011, 33.689, 2.245, 17.585]
}

In [3]:
index = ["Decision tree", "Logistic Regression", "KNN", "Random Forest", "AdaBoost", "GradientBoost", "LGBM", "XGBM"]

In [4]:
columns = ["Accuracy", "cross_val_acc", "roc_auc", "f1_score", "diff_cv_acc",  "speed_fit", "speed_cv"]

In [5]:
df = pd.DataFrame(data, index = index)
df

Accuracy  cross_val_acc  roc_auc  f1_score  diff_cv_acc  \
Decision tree          85.360           84.6   85.360    85.387        0.407   
Logistic Regression    79.840           79.0   87.506    79.781        0.840   
KNN                    96.953           96.6   99.039    96.954        0.353   
Random Forest          96.447           95.7   98.995    96.426        0.747   
AdaBoost               81.733           81.0   89.740    81.763        0.733   
GradientBoost          89.767           89.1   96.100    89.682        0.667   
LGBM                   95.853           95.5   98.927    95.843        0.353   
XGBM                   97.107           96.8   99.176    97.107        0.307   

                     speed_fit  speed_cv  
Decision tree            1.697     3.897  
Logistic Regression      0.167     2.175  
KNN                     14.949    23.285  
Random Forest           20.749    17.100  
AdaBoost                16.277    15.011  
GradientBoost           38.910    33.689  
LGBM                     0.364     2.245  
XGBM                     4.699    17.585

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
scaler = StandardScaler()

In [8]:
scaled_df = scaler.fit_transform(df)

In [9]:
df = pd.DataFrame(scaled_df, index = index, columns = columns)
df

Accuracy  cross_val_acc   roc_auc  f1_score  diff_cv_acc  \
Decision tree       -0.741882      -0.748606 -1.643088 -0.735514    -0.711419   
Logistic Regression -1.557250      -1.556740 -1.251101 -1.563339     1.429638   
KNN                  0.970539       0.983109  0.855507  0.972557    -0.978434   
Random Forest        0.895797       0.853231  0.847470  0.894589     0.969780   
AdaBoost            -1.277632      -1.268121 -0.843041 -1.270662     0.900554   
GradientBoost       -0.090917      -0.099213  0.318672 -0.101282     0.574204   
LGBM                 0.808057       0.824369  0.835049  0.808499    -0.978434   
XGBM                 0.993287       1.011971  0.880531  0.995151    -1.205890   

                     speed_fit  speed_cv  
Decision tree        -0.838297 -1.000979  
Logistic Regression  -0.960107 -1.165510  
KNN                   0.216750  0.851473  
Random Forest         0.678512  0.260519  
AdaBoost              0.322477  0.060923  
GradientBoost         2.124385  1.845537  
LGBM                 -0.944423 -1.158822  
XGBM                 -0.599296  0.306859

### Weighted Normalization

In [10]:
weights = [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

In [11]:
for i in range(len(df.columns)):
    df[df.columns[i]] = df[df.columns[i]] * weights[i] 
df

Accuracy  cross_val_acc   roc_auc  f1_score  diff_cv_acc  \
Decision tree       -0.370941      -0.374303 -0.821544 -0.367757    -0.355710   
Logistic Regression -0.778625      -0.778370 -0.625551 -0.781669     0.714819   
KNN                  0.485270       0.491555  0.427754  0.486279    -0.489217   
Random Forest        0.447899       0.426615  0.423735  0.447294     0.484890   
AdaBoost            -0.638816      -0.634060 -0.421520 -0.635331     0.450277   
GradientBoost       -0.045458      -0.049606  0.159336 -0.050641     0.287102   
LGBM                 0.404028       0.412184  0.417525  0.404249    -0.489217   
XGBM                 0.496644       0.505986  0.440266  0.497575    -0.602945   

                     speed_fit  speed_cv  
Decision tree        -0.419149 -0.500490  
Logistic Regression  -0.480054 -0.582755  
KNN                   0.108375  0.425737  
Random Forest         0.339256  0.130260  
AdaBoost              0.161239  0.030461  
GradientBoost         1.062192  0.922769  
LGBM                 -0.472212 -0.579411  
XGBM                 -0.299648  0.153430

### Ideal and Neg_Ideal Solution

In [12]:
criteria = ["Accuracy","cross_val_acc","roc_auc","f1_score", "diff_cv_acc", "speed_fit", "speed_cv" ]
benefit_criteria = ["Accuracy","cross_val_acc","roc_auc","f1_score"]
cost_criteria = ["diff_cv_acc", "speed_fit", "speed_cv"]

In [13]:
A_pos = []
for i in criteria:
    if i in benefit_criteria:
        A_pos.append(df[i].max())
    elif i in cost_criteria:
        A_pos.append(df[i].min())
A_pos = np.round(A_pos, decimals=3)
A_pos  

array([ 0.497,  0.506,  0.44 ,  0.498, -0.603, -0.48 , -0.583])

In [14]:
A_neg = []
for i in criteria:
    if i in benefit_criteria:
        A_neg.append(df[i].min())
    elif i in cost_criteria:
        A_neg.append(df[i].max())
A_neg = np.round(A_neg, decimals=3)
A_neg        

array([-0.779, -0.778, -0.822, -0.782,  0.715,  1.062,  0.923])

### Separation From Positve Ideal Solution

In [15]:
pos_data = df.copy()
for i in range(len(df.columns)):
    pos_data[pos_data.columns[i]] = (pos_data[pos_data.columns[i]] - A_pos[i]) ** 2
pos_data

Accuracy  cross_val_acc       roc_auc      f1_score  \
Decision tree        7.533214e-01   7.749335e-01  1.591493e+00  7.495352e-01   
Logistic Regression  1.627219e+00   1.649606e+00  1.135398e+00  1.637554e+00   
KNN                  1.375996e-04   2.086684e-04  1.499767e-04  1.373880e-04   
Random Forest        2.410941e-03   6.301929e-03  2.645502e-04  2.571049e-03   
AdaBoost             1.290078e+00   1.299738e+00  7.422172e-01  1.284439e+00   
GradientBoost        2.942610e-01   3.086985e-01  7.877236e-02  3.010067e-01   
LGBM                 8.643736e-03   8.801376e-03  5.051441e-04  8.789181e-03   
XGBM                 1.270839e-07   2.072720e-10  7.057201e-08  1.803590e-07   

                      diff_cv_acc     speed_fit      speed_cv  
Decision tree        6.115247e-02  3.702877e-03  6.807958e-03  
Logistic Regression  1.736647e+00  2.870146e-09  6.000260e-08  
KNN                  1.294662e-02  3.461849e-01  1.017549e+00  
Random Forest        1.183505e+00  6.711802e-01  5.087391e-01  
AdaBoost             1.109393e+00  4.111870e-01  3.763348e-01  
GradientBoost        7.922815e-01  2.378357e+00  2.267339e+00  
LGBM                 1.294662e-02  6.065953e-05  1.288147e-05  
XGBM                 3.023688e-09  3.252690e-02  5.423284e-01

In [16]:
sep_ideal=[]
for i in range(len(df)):
    sep_ideal.append(np.sqrt(sum(pos_data.iloc[i])))
sep_ideal = np.round(sep_ideal, decimals=3)
sep_ideal

array([1.985, 2.79 , 1.174, 1.541, 2.552, 2.534, 0.199, 0.758])

### Separation From Negative Ideal Solution

In [17]:
neg_data = df.copy()
for i in range(len(df.columns)):
    neg_data[neg_data.columns[i]] = (neg_data[neg_data.columns[i]] - A_neg[i]) ** 2
neg_data

Accuracy  cross_val_acc       roc_auc      f1_score  \
Decision tree        1.665122e-01   1.629712e-01  2.081041e-07  1.715973e-01   
Logistic Regression  1.405793e-07   1.369072e-07  3.859239e-02  1.093114e-07   
KNN                  1.598378e+00   1.611769e+00  1.561884e+00  1.608531e+00   
Random Forest        1.505280e+00   1.451098e+00  1.551856e+00  1.511165e+00   
AdaBoost             1.965156e-02   2.071861e-02  1.603840e-01  2.151187e-02   
GradientBoost        5.380835e-01   5.305572e-01  9.630201e-01  5.348863e-01   
LGBM                 1.399556e+00   1.416539e+00  1.536421e+00  1.407188e+00   
XGBM                 1.627266e+00   1.648619e+00  1.593315e+00  1.637313e+00   

                      diff_cv_acc     speed_fit      speed_cv  
Decision tree        1.146419e+00  2.193802e+00  2.026323e+00  
Logistic Regression  3.277147e-08  2.377929e+00  2.267298e+00  
KNN                  1.450138e+00  9.094010e-01  2.472709e-01  
Random Forest        5.295053e-02  5.223590e-01  6.284375e-01  
AdaBoost             7.007814e-02  8.113711e-01  7.966252e-01  
GradientBoost        1.830967e-01  3.702693e-08  5.352665e-08  
LGBM                 1.450138e+00  2.353805e+00  2.257239e+00  
XGBM                 1.736979e+00  1.854085e+00  5.922387e-01

In [18]:
sep_neg_ideal=[]
for i in range(len(df)):
    sep_neg_ideal.append(np.sqrt(sum(neg_data.iloc[i])))
sep_neg_ideal = np.round(sep_neg_ideal, decimals=3)
sep_neg_ideal

array([2.422, 2.164, 2.998, 2.688, 1.379, 1.658, 3.438, 3.27 ])

### Relative Closeness

In [19]:
C = []

for i in range(len(df)):
    c = sep_neg_ideal[i]/(sep_ideal[i] + sep_neg_ideal[i])
    C.append(c)
#C = np.round(C, decimals=2)
C

[0.5495802132970274,
 0.436818732337505,
 0.7186001917545541,
 0.6356112556159849,
 0.3508013228186212,
 0.3955152671755725,
 0.9452845751993402,
 0.8118172790466732]

In [20]:
rank =  np.array([sorted(C, reverse = True).index(x) for x in C]) + [1]
rank
df["rank"] = rank
df

Accuracy  cross_val_acc   roc_auc  f1_score  diff_cv_acc  \
Decision tree       -0.370941      -0.374303 -0.821544 -0.367757    -0.355710   
Logistic Regression -0.778625      -0.778370 -0.625551 -0.781669     0.714819   
KNN                  0.485270       0.491555  0.427754  0.486279    -0.489217   
Random Forest        0.447899       0.426615  0.423735  0.447294     0.484890   
AdaBoost            -0.638816      -0.634060 -0.421520 -0.635331     0.450277   
GradientBoost       -0.045458      -0.049606  0.159336 -0.050641     0.287102   
LGBM                 0.404028       0.412184  0.417525  0.404249    -0.489217   
XGBM                 0.496644       0.505986  0.440266  0.497575    -0.602945   

                     speed_fit  speed_cv  rank  
Decision tree        -0.419149 -0.500490     5  
Logistic Regression  -0.480054 -0.582755     6  
KNN                   0.108375  0.425737     3  
Random Forest         0.339256  0.130260     4  
AdaBoost              0.161239  0.030461     8  
GradientBoost         1.062192  0.922769     7  
LGBM                 -0.472212 -0.579411     1  
XGBM                 -0.299648  0.153430     2

In [21]:
print(f"By the TOPSIS method, Your choice should be '{df.index[C.index(max(C))].capitalize()}'.")

By the TOPSIS method, Your choice should be 'Lgbm'.


In [24]:
new_df = df.sort_values('rank')
new_df

Accuracy  cross_val_acc   roc_auc  f1_score  diff_cv_acc  \
LGBM                 0.404028       0.412184  0.417525  0.404249    -0.489217   
XGBM                 0.496644       0.505986  0.440266  0.497575    -0.602945   
KNN                  0.485270       0.491555  0.427754  0.486279    -0.489217   
Random Forest        0.447899       0.426615  0.423735  0.447294     0.484890   
Decision tree       -0.370941      -0.374303 -0.821544 -0.367757    -0.355710   
Logistic Regression -0.778625      -0.778370 -0.625551 -0.781669     0.714819   
GradientBoost       -0.045458      -0.049606  0.159336 -0.050641     0.287102   
AdaBoost            -0.638816      -0.634060 -0.421520 -0.635331     0.450277   

                     speed_fit  speed_cv  rank  
LGBM                 -0.472212 -0.579411     1  
XGBM                 -0.299648  0.153430     2  
KNN                   0.108375  0.425737     3  
Random Forest         0.339256  0.130260     4  
Decision tree        -0.419149 -0.500490     5  
Logistic Regression  -0.480054 -0.582755     6  
GradientBoost         1.062192  0.922769     7  
AdaBoost              0.161239  0.030461     8