In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Accuracy" : [86.432, 79.024, 97.204, 96.608, 81.14, 88.928, 95.508, 97.144],
    "cross_val_acc" : [86.3, 79.2, 97.0, 96.3, 81.4, 89.2, 95.8, 97.1],
    "roc_auc" : [86.432, 86.819, 99.028, 99.058, 89.467, 95.763, 98.858, 99.241],
    "f1_score" : [86.461, 78.93, 97.201, 96.588, 81.154, 88.821, 95.498, 97.139],
    "diff_cv_acc" : [0.132, 0.176, 0.204, 0.308, 0.26, 0.272, 0.292, 0.044],
    "speed_fit" : [3.171, 0.262, 37.918, 37.452, 28.579, 68.417, 0.472, 7.757],
    "speed_cv" : [5.295, 2.444, 59.557, 30.596, 27.657, 60.938, 2.801, 30.596]
}

In [3]:
index = ["Decision tree", "Logistic Regression", "KNN", "Random Forest", "AdaBoost", "GradientBoost", "LGBM", "XGBM"]

In [4]:
df = pd.DataFrame(data, index = index)
df

Accuracy  cross_val_acc  roc_auc  f1_score  diff_cv_acc  \
Decision tree          86.432           86.3   86.432    86.461        0.132   
Logistic Regression    79.024           79.2   86.819    78.930        0.176   
KNN                    97.204           97.0   99.028    97.201        0.204   
Random Forest          96.608           96.3   99.058    96.588        0.308   
AdaBoost               81.140           81.4   89.467    81.154        0.260   
GradientBoost          88.928           89.2   95.763    88.821        0.272   
LGBM                   95.508           95.8   98.858    95.498        0.292   
XGBM                   97.144           97.1   99.241    97.139        0.044   

                     speed_fit  speed_cv  
Decision tree            3.171     5.295  
Logistic Regression      0.262     2.444  
KNN                     37.918    59.557  
Random Forest           37.452    30.596  
AdaBoost                28.579    27.657  
GradientBoost           68.417    60.938  
LGBM                     0.472     2.801  
XGBM                     7.757    30.596

### Normalization

In [5]:
columns = ["Accuracy", "cross_val_acc", "roc_auc", "f1_score", "diff_cv_acc",  "speed_fit", "speed_cv"]

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_df = scaler.fit_transform(df)
df = pd.DataFrame(scaled_df, index = index, columns = columns)
df

Accuracy  cross_val_acc   roc_auc  f1_score  diff_cv_acc  \
Decision tree       -0.547104      -0.580858 -1.462375 -0.538424    -0.931866   
Logistic Regression -1.609059      -1.615113 -1.390748 -1.615988    -0.412852   
KNN                  0.997088       0.977808  0.868911  0.998295    -0.082570   
Random Forest        0.911650       0.875839  0.874464  0.910585     1.144189   
AdaBoost            -1.305725      -1.294640 -0.900653 -1.297770     0.577993   
GradientBoost       -0.189297      -0.158416  0.264620 -0.200747     0.719542   
LGBM                 0.753962       0.803004  0.837447  0.754624     0.955457   
XGBM                 0.988487       0.992375  0.908333  0.989424    -1.969893   

                     speed_fit  speed_cv  
Decision tree        -0.868118 -1.005567  
Logistic Regression  -0.995452 -1.134760  
KNN                   0.652845  1.453326  
Random Forest         0.632447  0.140953  
AdaBoost              0.244053  0.007772  
GradientBoost         1.987861  1.515907  
LGBM                 -0.986259 -1.118583  
XGBM                 -0.667377  0.140953

### Weighted Normalization

In [7]:
weights = [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

In [8]:
for i in range(len(df.columns)):
    df[df.columns[i]] = df[df.columns[i]] * weights[i] 
df

Accuracy  cross_val_acc   roc_auc  f1_score  diff_cv_acc  \
Decision tree       -0.273552      -0.290429 -0.731187 -0.269212    -0.465933   
Logistic Regression -0.804530      -0.807556 -0.695374 -0.807994    -0.206426   
KNN                  0.498544       0.488904  0.434456  0.499148    -0.041285   
Random Forest        0.455825       0.437920  0.437232  0.455293     0.572095   
AdaBoost            -0.652863      -0.647320 -0.450326 -0.648885     0.288996   
GradientBoost       -0.094648      -0.079208  0.132310 -0.100373     0.359771   
LGBM                 0.376981       0.401502  0.418724  0.377312     0.477729   
XGBM                 0.494243       0.496187  0.454167  0.494712    -0.984947   

                     speed_fit  speed_cv  
Decision tree        -0.434059 -0.502783  
Logistic Regression  -0.497726 -0.567380  
KNN                   0.326422  0.726663  
Random Forest         0.316223  0.070476  
AdaBoost              0.122027  0.003886  
GradientBoost         0.993931  0.757953  
LGBM                 -0.493130 -0.559291  
XGBM                 -0.333688  0.070476

### Ideal and Neg_Ideal Solution

In [9]:
criteria = ["Accuracy","cross_val_acc","roc_auc","f1_score", "diff_cv_acc", "speed_fit", "speed_cv" ]
benefit_criteria = ["Accuracy","cross_val_acc","roc_auc","f1_score"]
cost_criteria = ["diff_cv_acc", "speed_fit", "speed_cv"]

In [10]:
A_pos = []
for i in criteria:
    if i in benefit_criteria:
        A_pos.append(df[i].max())
    elif i in cost_criteria:
        A_pos.append(df[i].min())
A_pos = np.round(A_pos, decimals=3)
A_pos  

array([ 0.499,  0.496,  0.454,  0.499, -0.985, -0.498, -0.567])

In [11]:
A_neg = []
for i in criteria:
    if i in benefit_criteria:
        A_neg.append(df[i].min())
    elif i in cost_criteria:
        A_neg.append(df[i].max())
A_neg = np.round(A_neg, decimals=3)
A_neg        

array([-0.805, -0.808, -0.731, -0.808,  0.572,  0.994,  0.758])

### Separation From Positve Ideal Solution

In [12]:
pos_data = df.copy()
for i in range(len(df.columns)):
    pos_data[pos_data.columns[i]] = (pos_data[pos_data.columns[i]] - A_pos[i]) ** 2
pos_data

Accuracy  cross_val_acc       roc_auc      f1_score  \
Decision tree        5.968370e-01   6.184706e-01  1.404669e+00  5.901498e-01   
Logistic Regression  1.699189e+00   1.699260e+00  1.321061e+00  1.708233e+00   
KNN                  2.080799e-07   5.035336e-05  3.819855e-04  2.182154e-08   
Random Forest        1.864096e-03   3.373334e-03  2.811734e-04  1.910341e-03   
AdaBoost             1.326788e+00   1.307180e+00  8.178060e-01  1.317640e+00   
GradientBoost        3.524185e-01   3.308641e-01  1.034844e-01  3.592483e-01   
LGBM                 1.488864e-02   8.929842e-03  1.244422e-03  1.480800e-02   
XGBM                 2.262648e-05   3.514721e-08  2.779717e-08  1.838588e-05   

                      diff_cv_acc     speed_fit      speed_cv  
Decision tree        2.694308e-01  4.088482e-03  4.123768e-03  
Logistic Regression  6.061776e-01  7.517552e-08  1.445857e-07  
KNN                  8.905977e-01  6.796721e-01  1.673564e+00  
Random Forest        2.424544e+00  6.629595e-01  4.063762e-01  
AdaBoost             1.623067e+00  3.844331e-01  3.259106e-01  
GradientBoost        1.808409e+00  2.225857e+00  1.755501e+00  
LGBM                 2.139575e+00  2.371973e-05  5.942125e-05  
XGBM                 2.859392e-09  2.699827e-02  4.063762e-01

In [13]:
sep_ideal=[]
for i in range(len(df)):
    sep_ideal.append(np.sqrt(sum(pos_data.iloc[i])))
sep_ideal = np.round(sep_ideal, decimals=3)
sep_ideal

array([1.868, 2.652, 1.801, 1.871, 2.665, 2.634, 1.476, 0.658])

### Separation From Negative Ideal Solution

In [14]:
neg_data = df.copy()
for i in range(len(df.columns)):
    neg_data[neg_data.columns[i]] = (neg_data[neg_data.columns[i]] - A_neg[i]) ** 2
neg_data

Accuracy  cross_val_acc       roc_auc      f1_score  \
Decision tree        2.824367e-01   2.678797e-01  3.510900e-08  2.902924e-01   
Logistic Regression  2.213134e-07   1.966945e-07  1.269204e-03  3.561481e-11   
KNN                  1.699227e+00   1.681960e+00  1.358287e+00  1.708635e+00   
Random Forest        1.589679e+00   1.552316e+00  1.364765e+00  1.595908e+00   
AdaBoost             2.314575e-02   2.581812e-02  7.877773e-02  2.531762e-02   
GradientBoost        5.045994e-01   5.311379e-01  7.453043e-01  5.007356e-01   
LGBM                 1.397079e+00   1.462895e+00  1.321864e+00  1.404964e+00   
XGBM                 1.688033e+00   1.700905e+00  1.404620e+00  1.697059e+00   

                      diff_cv_acc     speed_fit      speed_cv  
Decision tree        1.077304e+00  2.039352e+00  1.589575e+00  
Logistic Regression  6.059469e-01  2.225246e+00  1.756633e+00  
KNN                  3.761187e-01  4.456600e-01  9.819976e-04  
Random Forest        8.966039e-09  4.593813e-01  4.726886e-01  
AdaBoost             8.009110e-02  7.603374e-01  5.686883e-01  
GradientBoost        4.504120e-02  4.824197e-09  2.180669e-09  
LGBM                 8.887105e-03  2.211555e+00  1.735257e+00  
XGBM                 2.424082e+00  1.762757e+00  4.726886e-01

In [15]:
sep_neg_ideal=[]
for i in range(len(df)):
    sep_neg_ideal.append(np.sqrt(sum(neg_data.iloc[i])))
sep_neg_ideal = np.round(sep_neg_ideal, decimals=3)
sep_neg_ideal

array([2.355, 2.142, 2.696, 2.652, 1.25 , 1.525, 3.089, 3.339])

### Relative Closeness

In [16]:
C = []

for i in range(len(df)):
    c = sep_neg_ideal[i]/(sep_ideal[i] + sep_neg_ideal[i])
    C.append(c)
#C = np.round(C, decimals=2)
C

[0.5576604309732418,
 0.4468085106382978,
 0.5995107849677563,
 0.5863365023214682,
 0.31928480204342274,
 0.3666746814138014,
 0.6766703176341731,
 0.8353765323992995]

In [17]:
rank =  np.array([sorted(C, reverse = True).index(x) for x in C]) + [1]
rank
df["rank"] = rank
df

Accuracy  cross_val_acc   roc_auc  f1_score  diff_cv_acc  \
Decision tree       -0.273552      -0.290429 -0.731187 -0.269212    -0.465933   
Logistic Regression -0.804530      -0.807556 -0.695374 -0.807994    -0.206426   
KNN                  0.498544       0.488904  0.434456  0.499148    -0.041285   
Random Forest        0.455825       0.437920  0.437232  0.455293     0.572095   
AdaBoost            -0.652863      -0.647320 -0.450326 -0.648885     0.288996   
GradientBoost       -0.094648      -0.079208  0.132310 -0.100373     0.359771   
LGBM                 0.376981       0.401502  0.418724  0.377312     0.477729   
XGBM                 0.494243       0.496187  0.454167  0.494712    -0.984947   

                     speed_fit  speed_cv  rank  
Decision tree        -0.434059 -0.502783     5  
Logistic Regression  -0.497726 -0.567380     6  
KNN                   0.326422  0.726663     3  
Random Forest         0.316223  0.070476     4  
AdaBoost              0.122027  0.003886     8  
GradientBoost         0.993931  0.757953     7  
LGBM                 -0.493130 -0.559291     2  
XGBM                 -0.333688  0.070476     1

In [18]:
print(f"By the TOPSIS method, Your choice should be '{df.index[C.index(max(C))].capitalize()}'.")

By the TOPSIS method, Your choice should be 'Xgbm'.


In [28]:
new_df = df.sort_values('rank')
new_df

Accuracy  cross_val_acc   roc_auc  f1_score  diff_cv_acc  \
XGBM                 0.494243       0.496187  0.454167  0.494712    -0.984947   
LGBM                 0.376981       0.401502  0.418724  0.377312     0.477729   
KNN                  0.498544       0.488904  0.434456  0.499148    -0.041285   
Random Forest        0.455825       0.437920  0.437232  0.455293     0.572095   
Decision tree       -0.273552      -0.290429 -0.731187 -0.269212    -0.465933   
Logistic Regression -0.804530      -0.807556 -0.695374 -0.807994    -0.206426   
GradientBoost       -0.094648      -0.079208  0.132310 -0.100373     0.359771   
AdaBoost            -0.652863      -0.647320 -0.450326 -0.648885     0.288996   

                     speed_fit  speed_cv  rank  
XGBM                 -0.333688  0.070476     1  
LGBM                 -0.493130 -0.559291     2  
KNN                   0.326422  0.726663     3  
Random Forest         0.316223  0.070476     4  
Decision tree        -0.434059 -0.502783     5  
Logistic Regression  -0.497726 -0.567380     6  
GradientBoost         0.993931  0.757953     7  
AdaBoost              0.122027  0.003886     8